/*
 * Parse a pasted buyer DM (generated by the shop's "Request to buy" flow,
 * but possibly edited by the buyer) back into records from the inventory.
 *
 * Pure functions only — the admin page owns all UI state. Nothing here
 * auto-selects anything; callers render the matched/ambiguous/unmatched
 * results and let the admin confirm.
 */

import type { DbRecord } from "./supabase";
import { REF_LINE_RE } from "./records";

export type ParsedLine = {
  raw: string;
  artist?: string;
  title?: string;
  media?: string;
  sleeve?: string;
  price?: number;
};

export type MatchStatus = "matched" | "ambiguous" | "unmatched";

export type LineMatch = {
  parsed: ParsedLine;
  status: MatchStatus;
  match?: DbRecord; // when matched
  candidates?: DbRecord[]; // top ≤3 when ambiguous
  flags?: string[]; // for the matched record: "sold", "on hold", price drift
};

export function extractRefCode(text: string): string | null {
  const m = text.match(REF_LINE_RE);
  return m ? m[1].toUpperCase() : null;
}

// Em/en dash or hyphen (optionally doubled) with surrounding space — the
// separator the DM uses, tolerating buyers retyping — as - or --.
const SEP = "\\s*[—–-]{1,2}\\s*";
const INDEX = "(?:\\d{1,3}[.)]\\s*)";
const PRICE = "(\\d+(?:\\.\\d{1,2})?)";

// 1. Artist — Title — Media: M / Sleeve: NM — $63
const FULL_LINE = new RegExp(
  `^\\s*${INDEX}?(.+?)${SEP}(.+?)${SEP}media:\\s*([^/]+?)\\s*/\\s*sleeve:\\s*(.+?)${SEP}\\$?\\s*${PRICE}\\s*$`,
  "i"
);
// Artist — Title — $63 (buyer deleted the grades)
const PRICED_LINE = new RegExp(
  `^\\s*${INDEX}?(.+?)${SEP}(.+?)${SEP}\\$\\s*${PRICE}\\s*$`,
  "i"
);
// 1. Artist — Title, or a bare Artist — Title. Un-numbered prose containing a
// dash also lands here, but that's safe: the matcher's score gate sends
// anything that doesn't resemble inventory to "unmatched".
const BARE_LINE = new RegExp(`^\\s*${INDEX}?(.+?)${SEP}(.+?)\\s*$`, "i");

const SKIP_LINE = /^\s*(subtotal|shipping|total)\b\s*[:(]/i;

function looksLikeItem(line: string) {
  return new RegExp(SEP).test(line) && line.trim().split(/\s+/).length >= 2;
}

export function parseOrderText(text: string): ParsedLine[] {
  const out: ParsedLine[] = [];
  for (const rawLine of text.split("\n")) {
    const raw = rawLine.trim();
    if (!raw || SKIP_LINE.test(raw) || REF_LINE_RE.test(raw)) continue;
    if (raw.includes("(Found on")) continue;

    let m = raw.match(FULL_LINE);
    if (m) {
      out.push({
        raw,
        artist: m[1].trim(),
        title: m[2].trim(),
        media: m[3].trim(),
        sleeve: m[4].trim(),
        price: Number(m[5]),
      });
      continue;
    }
    m = raw.match(PRICED_LINE);
    if (m) {
      out.push({ raw, artist: m[1].trim(), title: m[2].trim(), price: Number(m[3]) });
      continue;
    }
    m = raw.match(BARE_LINE);
    if (m) {
      out.push({ raw, artist: m[1].trim(), title: m[2].trim() });
      continue;
    }
    // Not parseable but shaped like an item — surface it so the admin sees
    // what didn't match instead of it silently disappearing.
    if (looksLikeItem(raw)) out.push({ raw });
  }
  return out;
}

export function normalize(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/['’`]/g, "") // "Devil's" and "Devils" normalize the same
    .replace(/[&+]/g, " and ")
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^the /, "");
}

function isOnHold(r: DbRecord) {
  return Boolean(r.hold_until && new Date(r.hold_until).getTime() > Date.now());
}

// Availability/price-drift notes for a record vs what the buyer's line said.
// Informational only — callers must never drop rows because of these.
export function recordFlags(r: DbRecord, parsedPrice?: number): string[] {
  const flags: string[] = [];
  if (r.sold) flags.push("sold");
  else if (isOnHold(r)) flags.push(r.hold_buyer ? `on hold for u/${r.hold_buyer}` : "on hold");
  if (parsedPrice !== undefined && Number(r.price) !== parsedPrice) {
    flags.push(`price now $${r.price} (was $${parsedPrice})`);
  }
  return flags;
}

function tokens(s: string): Set<string> {
  return new Set(s.split(" ").filter(Boolean));
}

function dice(a: Set<string>, b: Set<string>): number {
  if (a.size === 0 || b.size === 0) return 0;
  let overlap = 0;
  for (const t of a) if (b.has(t)) overlap++;
  return (2 * overlap) / (a.size + b.size);
}

const MATCH_SCORE = 0.85;
const MATCH_MARGIN = 0.15;
const CANDIDATE_SCORE = 0.5;

export function matchLines(lines: ParsedLine[], records: DbRecord[]): LineMatch[] {
  const index = records.map((r) => {
    const na = normalize(r.artist);
    const nt = normalize(r.title);
    return { r, na, nt, tokens: tokens(`${na} ${nt}`) };
  });

  return lines.map((parsed): LineMatch => {
    if (!parsed.artist || !parsed.title) return { parsed, status: "unmatched" };
    const pa = normalize(parsed.artist);
    const pt = normalize(parsed.title);

    // Exact tier on normalized artist + title; price breaks duplicate-copy ties.
    let exact = index.filter((e) => e.na === pa && e.nt === pt);
    if (exact.length > 1 && parsed.price !== undefined) {
      const byPrice = exact.filter((e) => Number(e.r.price) === parsed.price);
      if (byPrice.length === 1) exact = byPrice;
    }
    if (exact.length === 1) {
      const r = exact[0].r;
      return { parsed, status: "matched", match: r, flags: recordFlags(r, parsed.price) };
    }
    if (exact.length > 1) {
      return { parsed, status: "ambiguous", candidates: exact.slice(0, 3).map((e) => e.r) };
    }

    // Fuzzy tier: Dice coefficient over the combined artist+title token set,
    // so a shifted artist/title split (names containing " - ") still scores.
    const ptokens = tokens(`${pa} ${pt}`);
    const scored = index
      .map((e) => {
        let score = dice(ptokens, e.tokens);
        if (
          parsed.price !== undefined &&
          Math.abs(Number(e.r.price) - parsed.price) <= 1
        ) {
          score += 0.05;
        }
        return { r: e.r, score };
      })
      .sort((a, b) => b.score - a.score);

    const best = scored[0];
    const second = scored[1];
    if (!best || best.score < CANDIDATE_SCORE) return { parsed, status: "unmatched" };
    if (best.score >= MATCH_SCORE && (!second || best.score - second.score >= MATCH_MARGIN)) {
      return {
        parsed,
        status: "matched",
        match: best.r,
        flags: recordFlags(best.r, parsed.price),
      };
    }
    return {
      parsed,
      status: "ambiguous",
      candidates: scored
        .filter((s) => s.score >= CANDIDATE_SCORE)
        .slice(0, 3)
        .map((s) => s.r),
    };
  });
}
