// Server-only pick'em plumbing: The Odds API sync, score grading, and house
// picks generated by Claude. Imported only from route handlers.

import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { serviceSupabase } from "./supabase-service";
import { createServerSupabase } from "./supabase";
import {
  ALWAYS_FEATURED,
  LEAGUE_META,
  PICKEM_SEASON,
  seasonWeek,
  weekWindow,
  legLineAndPrice,
  type BestLine,
  type BestLines,
  type HouseCall,
  type HousePicks,
  type League,
  type Market,
  type PickemGame,
} from "./pickem";
import { isPower, unmappedTeams } from "./pickem-conferences";
import { espnDate, matchEvents, type EspnEvent, type LivePayload } from "./pickem-live";
import { buildParlays, parlaySignature, type ParlayDraft } from "./pickem-parlays";
import { buildHouseCard, projectionAgrees, type HouseCard } from "./pickem-house";

const oddsBase = (league: League) => `https://api.the-odds-api.com/v4/sports/${LEAGUE_META[league].oddsSport}`;
const SLATE_SIZE = 40; // college only; every NFL game of the week is on the board

export { authorizeJob } from "./job-auth";
export { serviceSupabase };

// ---------------------------------------------------------------------------
// The Odds API

type OddsOutcome = { name: string; price: number; point?: number };
type OddsMarket = { key: "spreads" | "totals" | "h2h"; outcomes: OddsOutcome[] };
type OddsBook = { key: string; title: string; markets: OddsMarket[] };
export type OddsEvent = {
  id: string;
  commence_time: string;
  home_team: string;
  away_team: string;
  bookmakers: OddsBook[];
};
type ScoreEvent = {
  id: string;
  commence_time: string;
  completed: boolean;
  home_team: string;
  away_team: string;
  scores: { name: string; score: string }[] | null;
};

function oddsKey(): string {
  const key = process.env.ODDS_API_KEY;
  if (!key) throw new Error("ODDS_API_KEY is not set");
  return key;
}

export async function fetchOdds(league: League): Promise<{ events: OddsEvent[]; remaining: string | null }> {
  const q = new URLSearchParams({
    apiKey: oddsKey(),
    regions: "us",
    markets: "spreads,totals,h2h",
    oddsFormat: "american",
    dateFormat: "iso",
  });
  const res = await fetch(`${oddsBase(league)}/odds?${q}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Odds API ${res.status}: ${await res.text()}`);
  return { events: await res.json(), remaining: res.headers.get("x-requests-remaining") };
}

export async function fetchScores(league: League, daysFrom = 3): Promise<ScoreEvent[]> {
  const q = new URLSearchParams({ apiKey: oddsKey(), daysFrom: String(daysFrom) });
  const res = await fetch(`${oddsBase(league)}/scores?${q}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Odds API scores ${res.status}: ${await res.text()}`);
  return res.json();
}

// ---------------------------------------------------------------------------
// Consensus + best number per game

function median(xs: number[]): number | null {
  if (!xs.length) return null;
  const s = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
}

export type LineSummary = {
  spread_home: number | null;
  total: number | null;
  ml_home: number | null;
  ml_away: number | null;
  best: BestLines;
};

export function summarizeEvent(ev: OddsEvent): LineSummary {
  const spreads: number[] = [];
  const totals: number[] = [];
  const mlHome: number[] = [];
  const mlAway: number[] = [];
  const best: BestLines = {};

  const better = (cur: BestLine | undefined, cand: BestLine, prefer: "high" | "low") => {
    if (!cur) return cand;
    const cp = cand.point ?? 0;
    const xp = cur.point ?? 0;
    if (cp === xp) return cand.price > cur.price ? cand : cur;
    return (prefer === "high" ? cp > xp : cp < xp) ? cand : cur;
  };

  for (const bk of ev.bookmakers) {
    for (const m of bk.markets) {
      for (const o of m.outcomes) {
        const line: BestLine = { point: o.point ?? null, price: o.price, book: bk.title };
        if (m.key === "spreads") {
          if (o.name === ev.home_team) {
            spreads.push(o.point ?? 0);
            best.spread_home = better(best.spread_home, line, "high");
          } else {
            best.spread_away = better(best.spread_away, line, "high");
          }
        } else if (m.key === "totals") {
          if (o.name === "Over") {
            totals.push(o.point ?? 0);
            best.over = better(best.over, line, "low");
          } else {
            best.under = better(best.under, line, "high");
          }
        } else if (m.key === "h2h") {
          if (o.name === ev.home_team) {
            mlHome.push(o.price);
            best.ml_home = better(best.ml_home, line, "high");
          } else {
            mlAway.push(o.price);
            best.ml_away = better(best.ml_away, line, "high");
          }
        }
      }
    }
  }
  const mh = median(mlHome);
  const ma = median(mlAway);
  return {
    spread_home: median(spreads),
    total: median(totals),
    ml_home: mh == null ? null : Math.round(mh),
    ml_away: ma == null ? null : Math.round(ma),
    best,
  };
}

// ---------------------------------------------------------------------------
// Slate selection. The NFL is every game of the week in kickoff order. College
// is capped at 40 and ordered closest spread first within tier:
//   0  anything Arkansas plays
//   1  Power Four vs Power Four
//   2  any game inside two touchdowns (competitive Group of Five games count)
//   3  Power Four vs anyone, inside four touchdowns
//   4  the rest
export function selectSlate(league: League, events: OddsEvent[], week: number): OddsEvent[] {
  const { start, end } = weekWindow(league, week);
  const inWeek = events.filter((e) => {
    const t = new Date(e.commence_time);
    return t >= start && t < end && e.bookmakers.length > 0;
  });
  if (league === "nfl") {
    return [...inWeek].sort((a, b) => a.commence_time.localeCompare(b.commence_time) || a.id.localeCompare(b.id));
  }
  const tier = (e: OddsEvent, spread: number) => {
    if (ALWAYS_FEATURED.includes(e.home_team) || ALWAYS_FEATURED.includes(e.away_team)) return 0;
    const p = Number(isPower(e.home_team)) + Number(isPower(e.away_team));
    if (p === 2) return 1;
    if (spread <= 14) return 2;
    if (p === 1 && spread <= 28) return 3;
    return 4;
  };
  return inWeek
    .map((e) => {
      const c = Math.abs(summarizeEvent(e).spread_home ?? 99);
      return { e, t: tier(e, c), c };
    })
    .sort((a, b) => a.t - b.t || a.c - b.c || a.e.commence_time.localeCompare(b.e.commence_time))
    .slice(0, SLATE_SIZE)
    .map((x) => x.e);
}

// ---------------------------------------------------------------------------
// Sync: pull lines, upsert the slate, record history, grade finished games.

export async function syncLines(league: League, now = new Date()) {
  const db = serviceSupabase();
  const week = seasonWeek(league, now);
  const { events, remaining } = await fetchOdds(league);
  const slate = selectSlate(league, events, week);

  // Keep games we already feature this week even if they fell out of the top
  // 40 (a line moved), so nobody's picks vanish.
  const { data: existing } = await db
    .from("pickem_games")
    .select("id, open_spread_home, open_total, open_ml_home, open_ml_away")
    .eq("league", league)
    .eq("season", PICKEM_SEASON)
    .eq("week", week);
  const existingById = new Map((existing ?? []).map((g) => [g.id, g]));
  const byId = new Map(slate.map((e) => [e.id, e]));
  for (const id of existingById.keys()) {
    const ev = events.find((e) => e.id === id);
    if (ev && !byId.has(id)) byId.set(id, ev);
  }

  const stamp = now.toISOString();
  const rows = [];
  const history = [];
  for (const ev of byId.values()) {
    const s = summarizeEvent(ev);
    const prev = existingById.get(ev.id);
    rows.push({
      id: ev.id,
      league,
      season: PICKEM_SEASON,
      week,
      commence_time: ev.commence_time,
      home_team: ev.home_team,
      away_team: ev.away_team,
      spread_home: s.spread_home,
      total: s.total,
      ml_home: s.ml_home,
      ml_away: s.ml_away,
      open_spread_home: prev?.open_spread_home ?? s.spread_home,
      open_total: prev?.open_total ?? s.total,
      open_ml_home: prev?.open_ml_home ?? s.ml_home,
      open_ml_away: prev?.open_ml_away ?? s.ml_away,
      best: s.best,
      lines_updated_at: stamp,
      updated_at: stamp,
    });
    history.push({
      game_id: ev.id,
      taken_at: stamp,
      spread_home: s.spread_home,
      total: s.total,
      ml_home: s.ml_home,
      ml_away: s.ml_away,
    });
  }

  if (rows.length) {
    const { error } = await db.from("pickem_games").upsert(rows, { onConflict: "id" });
    if (error) throw new Error(`upsert games: ${error.message}`);
    const { error: hErr } = await db.from("pickem_line_history").insert(history);
    if (hErr) throw new Error(`insert history: ${hErr.message}`);
  }

  // Grade: only spend a scores request when something needs a score. Scoped
  // to the league, since each feed only knows its own games.
  const { data: pending } = await db
    .from("pickem_games")
    .select("id, home_team, away_team")
    .eq("league", league)
    .eq("completed", false)
    .lte("commence_time", stamp)
    .gte("commence_time", new Date(now.getTime() - 3 * 86400000).toISOString());
  let graded = 0;
  if (pending && pending.length) {
    const scores = await fetchScores(league, 3);
    const byScoreId = new Map(scores.map((s) => [s.id, s]));
    for (const g of pending) {
      const s = byScoreId.get(g.id);
      if (!s?.completed || !s.scores) continue;
      const home = s.scores.find((x) => x.name === g.home_team);
      const away = s.scores.find((x) => x.name === g.away_team);
      if (!home || !away) continue;
      const { error } = await db
        .from("pickem_games")
        .update({
          home_score: Number(home.score),
          away_score: Number(away.score),
          completed: true,
          updated_at: stamp,
        })
        .eq("id", g.id);
      if (!error) graded++;
    }
  }

  // Team strings the conference map does not know. Genuine FCS opponents land
  // here too; anything FBS in this list is a spelling to add to the map.
  const unmapped = league === "ncaaf" ? unmappedTeams(rows.flatMap((r) => [r.home_team, r.away_team])) : [];
  return { league, week, games: rows.length, graded, unmapped_teams: unmapped, odds_requests_remaining: remaining };
}

// ---------------------------------------------------------------------------
// Live scores from ESPN's public scoreboard: no key, no Odds API credits.
// The board polls this while games are on. Finals it sees are written back,
// so picks grade within a minute of the game ending instead of at the next
// sync (which then finds nothing pending and spends no scores request).

const ESPN_SPORT: Record<League, string> = { ncaaf: "college-football", nfl: "nfl" };

/** One Eastern calendar day of games (ESPN rejects date ranges). */
export async function fetchEspnScoreboard(league: League, ymd: string): Promise<EspnEvent[]> {
  const q = new URLSearchParams({ dates: ymd, limit: "300" });
  if (league === "ncaaf") q.set("groups", "80"); // FBS; an FBS-FCS game is here too
  const res = await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/${ESPN_SPORT[league]}/scoreboard?${q}`, {
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`ESPN scoreboard ${res.status}`);
  const body = (await res.json()) as { events?: EspnEvent[] };
  return body.events ?? [];
}

// A game the sync has not graded, from a day and change back (so a night
// game the feed missed is retried the next day) to an hour ahead (ESPN
// sometimes has a kickoff a few minutes before the books do).
const LIVE_LOOKBACK_MS = 30 * 60 * 60 * 1000;
const LIVE_LOOKAHEAD_MS = 60 * 60 * 1000;

export async function liveScores(league: League, now = new Date()): Promise<LivePayload> {
  // Reading needs no secret; grading does. Without the service key (local
  // dev) the scores still flow and the sync grades later.
  const service = process.env.SUPABASE_SERVICE_ROLE_KEY ? serviceSupabase() : null;
  const db = service ?? createServerSupabase();
  const { data, error } = await db
    .from("pickem_games")
    .select("id, league, home_team, away_team, commence_time")
    .eq("league", league)
    .eq("completed", false)
    .gte("commence_time", new Date(now.getTime() - LIVE_LOOKBACK_MS).toISOString())
    .lte("commence_time", new Date(now.getTime() + LIVE_LOOKAHEAD_MS).toISOString());
  if (error) throw new Error(`read games: ${error.message}`);
  const pending = (data ?? []) as Pick<PickemGame, "id" | "league" | "home_team" | "away_team" | "commence_time">[];
  const asOf = now.toISOString();
  if (!pending.length) return { league, asOf, scores: {}, graded: 0, pending: 0 };

  const days = [...new Set(pending.map((g) => espnDate(Date.parse(g.commence_time))))];
  const events = (await Promise.all(days.map((d) => fetchEspnScoreboard(league, d)))).flat();
  const scores = matchEvents(league, pending, events);

  let graded = 0;
  if (service) {
    for (const [id, s] of Object.entries(scores)) {
      if (!s.completed) continue;
      const { error: uErr } = await service
        .from("pickem_games")
        .update({ home_score: s.home, away_score: s.away, completed: true, updated_at: asOf })
        .eq("id", id)
        .eq("completed", false);
      if (!uErr) graded++;
    }
  }
  return { league, asOf, scores, graded, pending: pending.length };
}

// ---------------------------------------------------------------------------
// House picks: Claude reads the slate in small batches and returns a pick,
// confidence and short rationale for every market of every game. Parlays are
// computed from those picks afterwards (lib/pickem-parlays.ts); the model no
// longer writes them.

// Sides are per market so the model cannot hand back "over" on a spread.
const callFields = { confidence: z.number().int().min(1).max(10), why: z.string().max(400) };
const SpreadCallSchema = z.object({ pick: z.enum(["home", "away"]), ...callFields });
const TotalCallSchema = z.object({ pick: z.enum(["over", "under"]), ...callFields });

// One batch of games. Array length cannot be enforced by the API's grammar,
// so completeness is checked in code after the call.
const HouseBatchSchema = z.object({
  games: z.array(
    z.object({
      game_id: z.string(),
      spread: SpreadCallSchema,
      total: TotalCallSchema,
      moneyline: SpreadCallSchema,
      projected_home: z.number().int().min(0).max(120),
      projected_away: z.number().int().min(0).max(120),
    })
  ),
});

const houseSystem = (league: League) => `You are the house handicapper for a friendly ${league === "nfl" ? "NFL" : "college football"} pick'em. For every game you get consensus lines (median across US books), the opening numbers we first recorded, and the best available number per side.

You receive a batch of games. Return exactly one entry for every game_id in the batch, in any order, and never omit a game. For each game give a pick for the spread, the total, and the moneyline with a confidence and a rationale of at most two sentences. Use line movement as a signal: money that moves a number is information. You may research recent results, injuries and quarterback news with web search; spend searches on the closest and highest-profile games in the batch, not on 40-point spreads.

Confidence is a calibrated probability that your pick wins on its own side of the number. 5 means the line is fair and you have no real lean (about 50% for spreads and totals; for a moneyline, the market's implied probability). 6 is about 55% to cover, 7 about 58%, 8 about 62%, 9 about 66%, and 10 is near-certain and almost never used. Never go below 5: if you would rather have the other side, pick the other side instead. Passing is normal and expected: a 5 means the market has it right, and on a typical slate roughly half of all calls are a 5. A 6 needs a reason you can name in the rationale; do not upgrade a coin flip to a 6 to seem decisive. A 7 is a real opinion, not a rarity: when the movement, the injury news and your research all point the same way, say so with a 7 or an 8 rather than hedging to a 6. The house stakes 1 unit on a 6, 2 on a 7 and 3 on an 8 or better, so a 7 is a call you would put two units on. Save 9 and 10 for the few numbers a season that are simply wrong. A full slate with no 7 on it is under-confident; a full slate with almost no 5s is over-confident.

Also give a projected final score for each game as whole points (projected_home, projected_away). Your spread call and total call must agree with the projection: the projected margin must cover the side you picked against the number you were given, and the projected total must fall on the side of the total you picked. If your projection lands right on the number, that is a 5. Only the moneyline may disagree with the projection, when a dog's price is worth the risk.

Selections use "home"/"away" for spread and moneyline and "over"/"under" for totals. Return only the JSON.`;

// Batches run in one wave so a 41-game slate fits the route's 300 s limit.
const BATCH_SIZE = 7;
const BATCH_CONCURRENCY = 6;
const PER_CALL_MS = 200_000;
const ROUTE_BUDGET_MS = 250_000; // leaves room for the writes and the response
const LAUNCH_FLOOR_MS = 60_000; // do not start a batch with less than this left
const RETRY_FLOOR_MS = 90_000; // and do not start the retry pass with less than this

type BatchOutcome = {
  size: number;
  ok: boolean;
  ms: number;
  reason?: string;
  usage?: Anthropic.Messages.Usage;
  /** Projections that contradicted the model's own spread or total call and were not kept. */
  projections_dropped?: number;
};

export type HouseRunOptions = { force?: boolean; dry?: boolean; onlyParlays?: boolean };

export type HouseRunResult = {
  league: League;
  week: number;
  picked: number;
  missing: { id: string; game: string }[];
  batches: BatchOutcome[];
  parlays: { inserted: number; removed: number; kept: number; skipped_duplicates: number };
  preview?: { picks: Record<string, HousePicks>; parlays: ParlayDraft[]; card: HouseCard };
};

/** Deal items round-robin into ceil(n / size) batches so the interesting games spread out. */
function dealBatches<T>(xs: T[], size: number): T[][] {
  const n = Math.ceil(xs.length / size);
  const out: T[][] = Array.from({ length: n }, () => []);
  xs.forEach((x, i) => out[i % n].push(x));
  return out.filter((b) => b.length);
}

/** Run fn over items with at most `limit` in flight. fn must not throw. */
async function pool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  const worker = async () => {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i]);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

function batchInput(g: PickemGame) {
  return {
    game_id: g.id,
    kickoff_utc: g.commence_time,
    away: g.away_team,
    home: g.home_team,
    spread_home: g.spread_home,
    open_spread_home: g.open_spread_home,
    total: g.total,
    open_total: g.open_total,
    ml_home: g.ml_home,
    ml_away: g.ml_away,
    best: g.best,
  };
}

/**
 * The number and price the house took, written into the call so its record
 * is graded against what it actually saw, not the closing line. Same rule as
 * a player's pick (legLineAndPrice). A `force` re-pick re-locks upcoming
 * games at the current number, which is what a re-pick means; started games
 * are never re-picked, so a locked call never moves after kickoff.
 */
function lockLines(g: PickemGame, h: HousePicks): HousePicks {
  const lock = (m: Market, c: HouseCall): HouseCall => ({ ...c, ...legLineAndPrice(g, m, c.pick) });
  return { spread: lock("spread", h.spread), total: lock("total", h.total), ml: lock("ml", h.ml) };
}

async function pickBatch(
  client: Anthropic,
  league: League,
  batch: PickemGame[],
  now: Date,
  week: number,
  msLeft: number
): Promise<{ picks: Map<string, HousePicks>; outcome: BatchOutcome }> {
  const started = Date.now();
  const picks = new Map<string, HousePicks>();
  const fail = (reason: string) => ({ picks, outcome: { size: batch.length, ok: false, ms: Date.now() - started, reason } });
  try {
    const stream = client.messages.stream(
      {
        model: "claude-opus-5",
        max_tokens: 16000,
        thinking: { type: "adaptive" },
        output_config: { effort: "high", format: zodOutputFormat(HouseBatchSchema) },
        tools: [{ type: "web_search_20260209", name: "web_search", max_uses: 4 }],
        system: houseSystem(league),
        messages: [
          {
            role: "user",
            content: `Today is ${now.toUTCString()}. ${LEAGUE_META[league].label} ${PICKEM_SEASON} season, week ${week}. Batch of ${batch.length} games:\n${JSON.stringify(batch.map(batchInput))}`,
          },
        ],
      },
      { signal: AbortSignal.timeout(Math.max(1000, Math.min(PER_CALL_MS, msLeft))), maxRetries: 1 }
    );
    const message = await stream.finalMessage();
    if (message.stop_reason === "refusal") return fail("refusal");
    if (message.stop_reason === "max_tokens") return fail("max_tokens");
    const parsed = message.parsed_output;
    if (!parsed) return fail("unparseable");
    const byId = new Map(batch.map((g) => [g.id, g]));
    let projections_dropped = 0;
    for (const g of parsed.games) {
      const game = byId.get(g.game_id);
      if (!game) continue;
      const house = lockLines(game, { spread: g.spread, total: g.total, ml: g.moneyline });
      // The calls are the product; a projection that contradicts them is noise and is not kept.
      const projection = { home: g.projected_home, away: g.projected_away };
      if (projectionAgrees(house, projection)) house.projection = projection;
      else projections_dropped++;
      picks.set(g.game_id, house);
    }
    return { picks, outcome: { size: batch.length, ok: true, ms: Date.now() - started, usage: message.usage, projections_dropped } };
  } catch (e) {
    const err = e as Error & { name?: string };
    const reason = e instanceof Anthropic.APIUserAbortError || err.name === "TimeoutError" ? "timeout" : err.message;
    return fail(reason);
  }
}

/** Replace the week's open, untailed parlays with the computed set. Tailed and locked tickets stay. */
async function rebuildParlays(
  db: ReturnType<typeof serviceSupabase>,
  league: League,
  games: PickemGame[],
  now: Date,
  week: number,
  dry: boolean
): Promise<HouseRunResult["parlays"] & { drafts: ParlayDraft[] }> {
  const drafts = buildParlays(games, now.getTime());
  const { data: open, error } = await db
    .from("pickem_parlays")
    .select("id, legs")
    .eq("league", league)
    .eq("season", PICKEM_SEASON)
    .eq("week", week)
    .gt("locks_at", now.toISOString());
  if (error) throw new Error(error.message);
  const openRows = (open ?? []) as { id: number; legs: ParlayDraft["legs"] }[];
  let tailed = new Set<number>();
  if (openRows.length) {
    const { data: t } = await db
      .from("pickem_parlay_tails")
      .select("parlay_id")
      .in("parlay_id", openRows.map((r) => r.id));
    tailed = new Set((t ?? []).map((r) => r.parlay_id as number));
  }
  const keptSignatures = new Set(openRows.filter((r) => tailed.has(r.id)).map((r) => parlaySignature(r.legs)));
  const fresh = drafts.filter((d) => !keptSignatures.has(d.signature));
  const skipped_duplicates = drafts.length - fresh.length;
  if (dry) return { inserted: 0, removed: 0, kept: tailed.size, skipped_duplicates, drafts };

  const rows = fresh.map((d) => ({
    name: d.name,
    legs: d.legs,
    american_odds: d.american_odds,
    note: d.note,
    locks_at: d.locks_at,
    hit_probability: d.hit_probability,
  }));
  const { data, error: rpcErr } = await db.rpc("pickem_replace_parlays", { p_league: league, p_season: PICKEM_SEASON, p_week: week, p_rows: rows });
  if (rpcErr) throw new Error(rpcErr.message);
  const r = (Array.isArray(data) ? data[0] : data) as { removed: number; inserted: number } | null;
  return { inserted: r?.inserted ?? 0, removed: r?.removed ?? 0, kept: tailed.size, skipped_duplicates, drafts };
}

export async function generateHousePicks(league: League, now = new Date(), opts: HouseRunOptions = {}): Promise<HouseRunResult> {
  const db = serviceSupabase();
  const week = seasonWeek(league, now);
  const { data: games, error } = await db
    .from("pickem_games")
    .select("*")
    .eq("league", league)
    .eq("season", PICKEM_SEASON)
    .eq("week", week)
    .gt("commence_time", now.toISOString())
    .order("commence_time");
  if (error) throw new Error(error.message);
  const slate = (games ?? []) as PickemGame[];

  const deadline = Date.now() + ROUTE_BUDGET_MS;
  const batches: BatchOutcome[] = [];
  const picks = new Map<string, HousePicks>();
  const label = (g: PickemGame) => `${g.away_team} @ ${g.home_team}`;
  let missing: HouseRunResult["missing"] = [];

  if (!opts.onlyParlays) {
    const todo = (opts.force ? slate : slate.filter((g) => !g.house)).sort(
      (a, b) => Math.abs(a.spread_home ?? 99) - Math.abs(b.spread_home ?? 99)
    );
    if (todo.length) {
      const client = new Anthropic();
      const run = async (games: PickemGame[]) => {
        await pool(dealBatches(games, BATCH_SIZE), BATCH_CONCURRENCY, async (batch) => {
          const msLeft = deadline - Date.now();
          if (msLeft < LAUNCH_FLOOR_MS) {
            batches.push({ size: batch.length, ok: false, ms: 0, reason: "deadline" });
            return;
          }
          const { picks: got, outcome } = await pickBatch(client, league, batch, now, week, msLeft);
          for (const [id, house] of got) picks.set(id, house);
          batches.push(outcome);
        });
      };
      await run(todo);
      let left = todo.filter((g) => !picks.has(g.id));
      if (left.length && deadline - Date.now() > RETRY_FLOOR_MS) {
        await run(left);
        left = todo.filter((g) => !picks.has(g.id));
      }
      missing = left.map((g) => ({ id: g.id, game: label(g) }));
    }
  }

  let picked = 0;
  if (!opts.dry) {
    const stamp = now.toISOString();
    for (const [id, house] of picks) {
      const { error: uErr } = await db.from("pickem_games").update({ house, updated_at: stamp }).eq("id", id);
      if (!uErr) picked++;
    }
  }

  const withPicks = slate.map((g) => (picks.has(g.id) ? { ...g, house: picks.get(g.id)! } : g));
  const { drafts, ...parlays } = await rebuildParlays(db, league, withPicks, now, week, Boolean(opts.dry));

  const result: HouseRunResult = { league, week, picked, missing, batches, parlays };
  if (opts.dry) result.preview = { picks: Object.fromEntries(picks), parlays: drafts, card: buildHouseCard(withPicks) };
  return result;
}
