// Server-only pick'em plumbing: The Odds API sync, score grading, and house
// picks generated by Claude. Imported only from route handlers.

import { createClient } from "@supabase/supabase-js";
import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, ADMIN_EMAIL } from "./supabase";
import {
  ALWAYS_FEATURED,
  PICKEM_SEASON,
  parlayAmericanOdds,
  seasonWeek,
  shortTeam,
  weekWindow,
  type BestLine,
  type BestLines,
  type HousePicks,
  type Market,
  type ParlayLeg,
  type PickemGame,
  type Selection,
} from "./pickem";
import { isPower, unmappedTeams } from "./pickem-conferences";

const ODDS_BASE = "https://api.the-odds-api.com/v4/sports/americanfootball_ncaaf";
const SLATE_SIZE = 40;

// ---------------------------------------------------------------------------
// Auth for the job routes: Vercel cron sends `Authorization: Bearer $CRON_SECRET`;
// the admin page sends the owner's Supabase access token.

export async function authorizeJob(req: Request): Promise<boolean> {
  const header = req.headers.get("authorization") ?? "";
  const token = header.replace(/^Bearer\s+/i, "").trim();
  if (!token) return false;
  const secret = process.env.CRON_SECRET;
  if (secret && token === secret) return true;
  const anon = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false },
  });
  const { data } = await anon.auth.getUser(token);
  return data.user?.email === ADMIN_EMAIL;
}

export function serviceSupabase() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) throw new Error("SUPABASE_SERVICE_ROLE_KEY is not set");
  return createClient(SUPABASE_URL, key, { auth: { persistSession: false } });
}

// ---------------------------------------------------------------------------
// The Odds API

type OddsOutcome = { name: string; price: number; point?: number };
type OddsMarket = { key: "spreads" | "totals" | "h2h"; outcomes: OddsOutcome[] };
type OddsBook = { key: string; title: string; markets: OddsMarket[] };
export type OddsEvent = {
  id: string;
  commence_time: string;
  home_team: string;
  away_team: string;
  bookmakers: OddsBook[];
};
type ScoreEvent = {
  id: string;
  commence_time: string;
  completed: boolean;
  home_team: string;
  away_team: string;
  scores: { name: string; score: string }[] | null;
};

function oddsKey(): string {
  const key = process.env.ODDS_API_KEY;
  if (!key) throw new Error("ODDS_API_KEY is not set");
  return key;
}

export async function fetchOdds(): Promise<{ events: OddsEvent[]; remaining: string | null }> {
  const q = new URLSearchParams({
    apiKey: oddsKey(),
    regions: "us",
    markets: "spreads,totals,h2h",
    oddsFormat: "american",
    dateFormat: "iso",
  });
  const res = await fetch(`${ODDS_BASE}/odds?${q}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Odds API ${res.status}: ${await res.text()}`);
  return { events: await res.json(), remaining: res.headers.get("x-requests-remaining") };
}

export async function fetchScores(daysFrom = 3): Promise<ScoreEvent[]> {
  const q = new URLSearchParams({ apiKey: oddsKey(), daysFrom: String(daysFrom) });
  const res = await fetch(`${ODDS_BASE}/scores?${q}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Odds API scores ${res.status}: ${await res.text()}`);
  return res.json();
}

// ---------------------------------------------------------------------------
// Consensus + best number per game

function median(xs: number[]): number | null {
  if (!xs.length) return null;
  const s = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
}

export type LineSummary = {
  spread_home: number | null;
  total: number | null;
  ml_home: number | null;
  ml_away: number | null;
  best: BestLines;
};

export function summarizeEvent(ev: OddsEvent): LineSummary {
  const spreads: number[] = [];
  const totals: number[] = [];
  const mlHome: number[] = [];
  const mlAway: number[] = [];
  const best: BestLines = {};

  const better = (cur: BestLine | undefined, cand: BestLine, prefer: "high" | "low") => {
    if (!cur) return cand;
    const cp = cand.point ?? 0;
    const xp = cur.point ?? 0;
    if (cp === xp) return cand.price > cur.price ? cand : cur;
    return (prefer === "high" ? cp > xp : cp < xp) ? cand : cur;
  };

  for (const bk of ev.bookmakers) {
    for (const m of bk.markets) {
      for (const o of m.outcomes) {
        const line: BestLine = { point: o.point ?? null, price: o.price, book: bk.title };
        if (m.key === "spreads") {
          if (o.name === ev.home_team) {
            spreads.push(o.point ?? 0);
            best.spread_home = better(best.spread_home, line, "high");
          } else {
            best.spread_away = better(best.spread_away, line, "high");
          }
        } else if (m.key === "totals") {
          if (o.name === "Over") {
            totals.push(o.point ?? 0);
            best.over = better(best.over, line, "low");
          } else {
            best.under = better(best.under, line, "high");
          }
        } else if (m.key === "h2h") {
          if (o.name === ev.home_team) {
            mlHome.push(o.price);
            best.ml_home = better(best.ml_home, line, "high");
          } else {
            mlAway.push(o.price);
            best.ml_away = better(best.ml_away, line, "high");
          }
        }
      }
    }
  }
  const mh = median(mlHome);
  const ma = median(mlAway);
  return {
    spread_home: median(spreads),
    total: median(totals),
    ml_home: mh == null ? null : Math.round(mh),
    ml_away: ma == null ? null : Math.round(ma),
    best,
  };
}

// ---------------------------------------------------------------------------
// Slate selection, capped at 40 and ordered closest spread first within tier:
//   0  anything Arkansas plays
//   1  Power Four vs Power Four
//   2  any game inside two touchdowns (competitive Group of Five games count)
//   3  Power Four vs anyone, inside four touchdowns
//   4  the rest
export function selectSlate(events: OddsEvent[], week: number): OddsEvent[] {
  const { start, end } = weekWindow(week);
  const inWeek = events.filter((e) => {
    const t = new Date(e.commence_time);
    return t >= start && t < end && e.bookmakers.length > 0;
  });
  const tier = (e: OddsEvent, spread: number) => {
    if (ALWAYS_FEATURED.includes(e.home_team) || ALWAYS_FEATURED.includes(e.away_team)) return 0;
    const p = Number(isPower(e.home_team)) + Number(isPower(e.away_team));
    if (p === 2) return 1;
    if (spread <= 14) return 2;
    if (p === 1 && spread <= 28) return 3;
    return 4;
  };
  return inWeek
    .map((e) => {
      const c = Math.abs(summarizeEvent(e).spread_home ?? 99);
      return { e, t: tier(e, c), c };
    })
    .sort((a, b) => a.t - b.t || a.c - b.c || a.e.commence_time.localeCompare(b.e.commence_time))
    .slice(0, SLATE_SIZE)
    .map((x) => x.e);
}

// ---------------------------------------------------------------------------
// Sync: pull lines, upsert the slate, record history, grade finished games.

export async function syncLines(now = new Date()) {
  const db = serviceSupabase();
  const week = seasonWeek(now);
  const { events, remaining } = await fetchOdds();
  const slate = selectSlate(events, week);

  // Keep games we already feature this week even if they fell out of the top
  // 40 (a line moved), so nobody's picks vanish.
  const { data: existing } = await db
    .from("pickem_games")
    .select("id, open_spread_home, open_total, open_ml_home, open_ml_away")
    .eq("season", PICKEM_SEASON)
    .eq("week", week);
  const existingById = new Map((existing ?? []).map((g) => [g.id, g]));
  const byId = new Map(slate.map((e) => [e.id, e]));
  for (const id of existingById.keys()) {
    const ev = events.find((e) => e.id === id);
    if (ev && !byId.has(id)) byId.set(id, ev);
  }

  const stamp = now.toISOString();
  const rows = [];
  const history = [];
  for (const ev of byId.values()) {
    const s = summarizeEvent(ev);
    const prev = existingById.get(ev.id);
    rows.push({
      id: ev.id,
      season: PICKEM_SEASON,
      week,
      commence_time: ev.commence_time,
      home_team: ev.home_team,
      away_team: ev.away_team,
      spread_home: s.spread_home,
      total: s.total,
      ml_home: s.ml_home,
      ml_away: s.ml_away,
      open_spread_home: prev?.open_spread_home ?? s.spread_home,
      open_total: prev?.open_total ?? s.total,
      open_ml_home: prev?.open_ml_home ?? s.ml_home,
      open_ml_away: prev?.open_ml_away ?? s.ml_away,
      best: s.best,
      lines_updated_at: stamp,
      updated_at: stamp,
    });
    history.push({
      game_id: ev.id,
      taken_at: stamp,
      spread_home: s.spread_home,
      total: s.total,
      ml_home: s.ml_home,
      ml_away: s.ml_away,
    });
  }

  if (rows.length) {
    const { error } = await db.from("pickem_games").upsert(rows, { onConflict: "id" });
    if (error) throw new Error(`upsert games: ${error.message}`);
    const { error: hErr } = await db.from("pickem_line_history").insert(history);
    if (hErr) throw new Error(`insert history: ${hErr.message}`);
  }

  // Grade: only spend a scores request when something needs a score.
  const { data: pending } = await db
    .from("pickem_games")
    .select("id, home_team, away_team")
    .eq("completed", false)
    .lte("commence_time", stamp)
    .gte("commence_time", new Date(now.getTime() - 3 * 86400000).toISOString());
  let graded = 0;
  if (pending && pending.length) {
    const scores = await fetchScores(3);
    const byScoreId = new Map(scores.map((s) => [s.id, s]));
    for (const g of pending) {
      const s = byScoreId.get(g.id);
      if (!s?.completed || !s.scores) continue;
      const home = s.scores.find((x) => x.name === g.home_team);
      const away = s.scores.find((x) => x.name === g.away_team);
      if (!home || !away) continue;
      const { error } = await db
        .from("pickem_games")
        .update({
          home_score: Number(home.score),
          away_score: Number(away.score),
          completed: true,
          updated_at: stamp,
        })
        .eq("id", g.id);
      if (!error) graded++;
    }
  }

  // Team strings the conference map does not know. Genuine FCS opponents land
  // here too; anything FBS in this list is a spelling to add to the map.
  const unmapped = unmappedTeams(rows.flatMap((r) => [r.home_team, r.away_team]));
  return { week, games: rows.length, graded, unmapped_teams: unmapped, odds_requests_remaining: remaining };
}

// ---------------------------------------------------------------------------
// House picks: Claude reads the slate (with line movement) and returns a pick,
// confidence and short rationale for every market, plus 2-3 parlays.

const HouseCallSchema = z.object({
  pick: z.enum(["home", "away", "over", "under"]),
  confidence: z.number().int().min(1).max(10),
  why: z.string().max(400),
});

const HouseOutputSchema = z.object({
  games: z.array(
    z.object({
      game_id: z.string(),
      spread: HouseCallSchema,
      total: HouseCallSchema,
      moneyline: HouseCallSchema,
    })
  ),
  parlays: z
    .array(
      z.object({
        name: z.string().max(60),
        legs: z
          .array(
            z.object({
              game_id: z.string(),
              market: z.enum(["spread", "total", "ml"]),
              selection: z.enum(["home", "away", "over", "under"]),
            })
          )
          .min(2)
          .max(4),
        confidence: z.number().int().min(1).max(10),
        note: z.string().max(400),
      })
    )
    .min(2)
    .max(3),
});

const HOUSE_SYSTEM = `You are the house handicapper for a friendly college football pick'em. For every game you get consensus lines (median across US books), the opening numbers we first recorded, and the best available number per side.

For each game give a pick for the spread, the total, and the moneyline with a 1-10 confidence and a rationale of at most two sentences. Confidence 8+ should be rare. Use line movement as a signal: money that moves a number is information. You may research recent results, injuries and quarterback news with web search; spend searches on the closest and highest-profile games, not on 40-point spreads.

Then build two or three parlays from the slate. One should be a "safer" parlay of two or three heavy favorites on the moneyline; the others can mix spreads and totals. Legs must reference game_id values from the input and must not include two markets from the same game. Prefer legs where your confidence is 7 or higher.

Selections use "home"/"away" for spread and moneyline and "over"/"under" for totals. Return only the JSON.`;

function legLabel(g: PickemGame, market: Market, selection: Selection): string {
  const home = shortTeam(g.home_team);
  const away = shortTeam(g.away_team);
  if (market === "total") return `${selection === "over" ? "Over" : "Under"} ${g.total} (${away} @ ${home})`;
  const team = selection === "home" ? home : away;
  if (market === "ml") return `${team} ML`;
  const sp = selection === "home" ? g.spread_home : g.spread_home == null ? null : -g.spread_home;
  return `${team} ${sp == null ? "" : sp > 0 ? `+${sp}` : sp}`;
}

function legLineAndPrice(g: PickemGame, market: Market, selection: Selection): { line: number | null; price: number } {
  if (market === "ml") {
    return { line: null, price: (selection === "home" ? g.ml_home : g.ml_away) ?? -110 };
  }
  if (market === "total") {
    const b = selection === "over" ? g.best.over : g.best.under;
    return { line: g.total, price: b?.price ?? -110 };
  }
  const b = selection === "home" ? g.best.spread_home : g.best.spread_away;
  const line = selection === "home" ? g.spread_home : g.spread_home == null ? null : -g.spread_home;
  return { line, price: b?.price ?? -110 };
}

export async function generateHousePicks(now = new Date(), opts: { force?: boolean } = {}) {
  const db = serviceSupabase();
  const week = seasonWeek(now);
  const { data: games, error } = await db
    .from("pickem_games")
    .select("*")
    .eq("season", PICKEM_SEASON)
    .eq("week", week)
    .gt("commence_time", now.toISOString())
    .order("commence_time");
  if (error) throw new Error(error.message);
  const slate = (games ?? []) as PickemGame[];
  const todo = opts.force ? slate : slate.filter((g) => !g.house);
  if (!todo.length) return { week, picked: 0, parlays: 0, skipped: "nothing to pick" };

  const client = new Anthropic();
  const input = todo.map((g) => ({
    game_id: g.id,
    kickoff_utc: g.commence_time,
    away: g.away_team,
    home: g.home_team,
    spread_home: g.spread_home,
    open_spread_home: g.open_spread_home,
    total: g.total,
    open_total: g.open_total,
    ml_home: g.ml_home,
    ml_away: g.ml_away,
    best: g.best,
  }));

  const stream = client.messages.stream({
    model: "claude-opus-5",
    max_tokens: 32000,
    thinking: { type: "adaptive" },
    output_config: { effort: "high", format: zodOutputFormat(HouseOutputSchema) },
    tools: [{ type: "web_search_20260209", name: "web_search", max_uses: 12 }],
    system: HOUSE_SYSTEM,
    messages: [
      {
        role: "user",
        content: `Today is ${now.toUTCString()}. Season ${PICKEM_SEASON}, week ${week}. Slate:\n${JSON.stringify(input)}`,
      },
    ],
  });
  const message = await stream.finalMessage();
  if (message.stop_reason === "refusal") throw new Error("model declined the request");
  const text = message.content.find((b) => b.type === "text")?.text ?? "";
  const parsed = HouseOutputSchema.parse(JSON.parse(text));

  const byId = new Map(slate.map((g) => [g.id, g]));
  const stamp = now.toISOString();
  let picked = 0;
  for (const g of parsed.games) {
    if (!byId.has(g.game_id)) continue;
    const house: HousePicks = { spread: g.spread, total: g.total, ml: g.moneyline };
    const { error: uErr } = await db
      .from("pickem_games")
      .update({ house, updated_at: stamp })
      .eq("id", g.game_id);
    if (!uErr) picked++;
  }

  // Replace this week's house parlays only when we are (re)picking the slate.
  if (opts.force || !slate.some((g) => g.house)) {
    await db.from("pickem_parlays").delete().eq("season", PICKEM_SEASON).eq("week", week);
  }
  let parlays = 0;
  for (const p of parsed.parlays) {
    const legs: ParlayLeg[] = [];
    const seen = new Set<string>();
    for (const l of p.legs) {
      const g = byId.get(l.game_id);
      if (!g || seen.has(g.id)) continue;
      seen.add(g.id);
      const { line, price } = legLineAndPrice(g, l.market, l.selection);
      legs.push({ game_id: g.id, market: l.market, selection: l.selection, line, price, label: legLabel(g, l.market, l.selection) });
    }
    if (legs.length < 2) continue;
    const locks_at = legs
      .map((l) => byId.get(l.game_id)!.commence_time)
      .sort()[0];
    const { error: pErr } = await db.from("pickem_parlays").insert({
      season: PICKEM_SEASON,
      week,
      name: p.name,
      legs,
      american_odds: parlayAmericanOdds(legs.map((l) => l.price)),
      confidence: p.confidence,
      note: p.note,
      locks_at,
    });
    if (!pErr) parlays++;
  }

  return { week, picked, parlays, usage: message.usage };
}
