-- Orders: one row per sale, from the first hold or invoice through
-- fulfillment. Until now an order was reconstructed from the sale-desk
-- selection, an order_requests row, hold_buyer on each record, the
-- invoices row, and a fulfillment group keyed on the lowercased buyer
-- name — so two orders to one buyer merged, a typo split one, and the
-- buyer could only be renamed record by record. Records and parcels now
-- point at the order; the buyer name lives on it.
--
-- Status: held (records reserved, no invoice yet) → invoiced (PayPal
-- invoice out) → paid (records marked sold). cancelled ends either open
-- stage. "fulfilled" stays derived: every record in a tracked parcel.
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  buyer_username text not null default '',
  status text not null default 'held'
    check (status in ('held', 'invoiced', 'paid', 'cancelled')),
  paypal_invoice_id text,           -- the live invoice, if one was sent
  request_id bigint references public.order_requests(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_paypal_invoice_id_idx
  on public.orders (paypal_invoice_id);

alter table public.orders enable row level security;
drop policy if exists "admin full access to orders" on public.orders;
create policy "admin full access to orders" on public.orders
  for all
  using ((select auth.jwt() ->> 'email') = 'brandoncgillihan@gmail.com')
  with check ((select auth.jwt() ->> 'email') = 'brandoncgillihan@gmail.com');

alter table public.records
  add column if not exists order_id bigint references public.orders(id) on delete set null;
alter table public.shipments
  add column if not exists order_id bigint references public.orders(id) on delete set null;
create index if not exists records_order_id_idx on public.records (order_id);
create index if not exists shipments_order_id_idx on public.shipments (order_id);

comment on column public.records.order_id is
  'The order this record is held for, invoiced on, or sold in. Cleared when a hold is released or the record is un-sold.';
comment on column public.shipments.order_id is
  'The order this parcel belongs to; fulfillment groups parcels by it.';

-- ---------------------------------------------------------------------
-- Backfill from what the old model recorded.
-- ---------------------------------------------------------------------

-- A cancelled invoice that was never cleared off its unsold records (the
-- cancel route clears the stamp today; earlier cancels left it behind).
update public.records r
   set paypal_invoice_id = null, hold_buyer = null, hold_until = null,
       updated_at = now()
  from public.invoices i
 where i.paypal_invoice_id = r.paypal_invoice_id
   and i.status = 'CANCELLED'
   and not r.sold;

-- 1. One order per live invoice. Its records come from the stamp on the
--    records, or the ids saved with the invoice when the stamp never
--    landed. Paid when PayPal said so or when every record is sold.
with inv as (
  select i.paypal_invoice_id, i.buyer_username, i.paid_at, i.created_at,
         coalesce(
           nullif(array(select r.id from public.records r
                         where r.paypal_invoice_id = i.paypal_invoice_id), '{}'),
           i.record_ids
         ) as ids
    from public.invoices i
   where coalesce(i.status, '') <> 'CANCELLED'
)
insert into public.orders (buyer_username, status, paypal_invoice_id, created_at, updated_at)
select
  coalesce(
    nullif(trim(inv.buyer_username), ''),
    (select max(coalesce(nullif(trim(r.buyer_username), ''), r.hold_buyer))
       from public.records r where r.id = any(inv.ids)),
    ''),
  case
    when inv.paid_at is not null then 'paid'
    when (select bool_and(r.sold) from public.records r where r.id = any(inv.ids)) then 'paid'
    else 'invoiced'
  end,
  inv.paypal_invoice_id,
  inv.created_at,
  now()
  from inv
 where inv.ids is not null and cardinality(inv.ids) > 0;

update public.records r
   set order_id = o.id
  from public.orders o
 where o.paypal_invoice_id = r.paypal_invoice_id
   and r.order_id is null;

-- Invoices whose stamp never landed: link by the saved ids and restore
-- the stamp, unsold records only.
update public.records r
   set order_id = o.id, paypal_invoice_id = o.paypal_invoice_id, updated_at = now()
  from public.orders o
  join public.invoices i on i.paypal_invoice_id = o.paypal_invoice_id
 where r.order_id is null
   and not r.sold
   and r.id = any(i.record_ids);

-- 2. Sold records with no invoice: one paid order per buyer name, the
--    way fulfillment used to group them.
insert into public.orders (buyer_username, status, created_at, updated_at)
select min(r.buyer_username), 'paid', coalesce(min(r.sold_at), now()), now()
  from public.records r
 where r.sold and r.order_id is null
 group by lower(trim(r.buyer_username));

update public.records r
   set order_id = o.id
  from public.orders o
 where r.sold and r.order_id is null
   and o.paypal_invoice_id is null and o.status = 'paid'
   and lower(trim(r.buyer_username)) = lower(trim(o.buyer_username));

-- 3. Active holds with no invoice: one held order per buyer name.
insert into public.orders (buyer_username, status, created_at, updated_at)
select min(r.hold_buyer), 'held', now(), now()
  from public.records r
 where not r.sold and r.order_id is null
   and r.hold_until > now() and coalesce(trim(r.hold_buyer), '') <> ''
 group by lower(trim(r.hold_buyer));

update public.records r
   set order_id = o.id
  from public.orders o
 where not r.sold and r.order_id is null
   and r.hold_until > now()
   and o.status = 'held' and o.paypal_invoice_id is null
   and lower(trim(r.hold_buyer)) = lower(trim(o.buyer_username));

-- 4. Parcels follow their invoice, else the order of a member record.
update public.shipments s
   set order_id = o.id
  from public.orders o
 where s.order_id is null
   and s.paypal_invoice_id is not null
   and o.paypal_invoice_id = s.paypal_invoice_id;

update public.shipments s
   set order_id = r.order_id
  from public.records r
 where s.order_id is null
   and r.order_id is not null
   and r.id = any(s.record_ids);
